project_id: '816438'
api_token: 70f3fc562820d334fd7329abede970c98148dced4ed61a82866cee38b5a08271c282564c01f501ec
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
commit_message: New Crowdin updates
files:
  - source: /messages/en.json
    translation: /messages/%two_letters_code%.json
